# ==== some info ====
# Search by substring : C+F (and esc/C-c for exit)

[scrolling]
history=100000

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval=500

[keyboard]
bindings = [
  { key = "Back", mods = "Control", chars = "\u0017" },
  { key = "Delete", mods = "Control", chars = "\u001bd" },
]

# Color theme ported from iTerm 2 Smoooooth

# Colors (Wombat)

# Default colors
[colors.primary]
background = '#1f1f1f'
foreground = '#e5e1d8'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#f7786d'
green   = '#bde97c'
yellow  = '#efdfac'
blue    = '#6ebaf8'
magenta = '#ef88ff'
cyan    = '#90fdf8'
white   = '#e5e1d8'

# Bright colors
[colors.bright]
black   = '#b4b4b4'
red     = '#f99f92'
green   = '#e3f7a1'
yellow  = '#f2e9bf'
blue    = '#b3d2ff'
magenta = '#e5bdff'
cyan    = '#c2fefa'
white   = '#ffffff'

# [colors.primary]
# foreground = '#dbdbdb'
# background = '#1A1A1A'

# [colors.cursor]
# text   = '#000000'
# cursor = '#fefffe'

# [colors.selection]
# text       = '#000000'
# background = '#b3d7ff'

# [colors.normal]
# black   = '#14191e'
# red     = '#b43c29'
# green   = '#00c200'
# yellow  = '#c7c400'
# blue    = '#2743c7'
# magenta = '#bf3fbd'
# cyan    = '#00c5c7'
# white   = '#c7c7c7'

# [colors.bright]
# black   = '#676767'
# red     = '#dc7974'
# green   = '#57e690'
# yellow  = '#ece100'
# blue    = '#a6aaf1'
# magenta = '#e07de0'
# cyan    = '#5ffdff'
# white   = '#feffff'