# ==== some info ====
# Search by substring : C+F (and esc/C-c for exit)

[scrolling]
history=100000

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval=500

[keyboard]
bindings = [
  { key = "Back", mods = "Control", chars = "\u0017" },
  { key = "Delete", mods = "Control", chars = "\u001bd" },

  # check https://github.com/alacritty/alacritty/issues/5450
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]

# colortheme stolen from https://github.com/alacritty/alacritty-theme/blob/master/themes/vscode.toml

[colors.primary]
foreground = "#cccccc"
background = "#1e1e1e"

[colors.normal]
black = "#000000"
red = "#cd3131"
green = "#0dbc79"
yellow = "#e5e510"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#11a8cd"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#f14c4c"
green = "#23d18b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"
white = "#e5e5e5"